version: "3.1"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data/db

  todo_backend:
    container_name: todo_backend
    build: ./backend
    image: isp-backend:1.0
    ports:
      - "15000:15000"
    volumes:
      - ./backend:/app

    depends_on:
      - mongo

  todo_frontend:
    container_name: todo_frontend
    build: ./frontend
    image: isp-frontend:1.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - todo_backend